version: '3.8'

services:
  app:
    build: .
    container_name: java-gradle-app
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    volumes:
      - .:/app
    working_dir: /app
    command: gradle run
